<template>
    <div class="">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Example Component</div>

                    <div class="card-body">
                        I'm an example component.
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur consequuntur dolores esse eveniet incidunt laboriosam perferendis rem similique tenetur voluptate? Ab accusantium animi, blanditiis commodi cum cumque dolore eaque et eum expedita explicabo facilis fugiat fugit id in ipsa labore magnam mollitia natus nihil nobis nostrum obcaecati odio, omnis pariatur placeat provident quibusdam recusandae repellat repellendus sunt tempore voluptate voluptates. Ad aliquam, aliquid architecto assumenda dignissimos doloribus dolorum ea esse excepturi fuga harum ipsa, iusto magnam modi necessitatibus neque nihil numquam officiis, omnis perferendis quas qui quia quos ratione reiciendis repellendus sed tenetur ullam ut vitae. Aliquid corporis dicta eaque eligendi esse eum facere ipsum, iure, iusto laborum nihil officia optio quaerat rerum sequi sint tempore! Adipisci alias, commodi cupiditate doloremque earum eum eveniet, harum molestias necessitatibus nemo placeat provident quaerat quasi recusandae rerum saepe sapiente sequi similique ullam voluptate? Aperiam asperiores at, corporis, deleniti dolor doloribus eaque harum libero nulla placeat repellat tempora! Aperiam atque commodi culpa cupiditate delectus dicta dolores doloribus ducimus eius eos esse eveniet facere harum hic, inventore ipsa ipsum maiores necessitatibus odio quae, quam quasi qui quisquam quos repudiandae rerum sit. A consectetur cumque deserunt hic nihil nisi quas similique. Consequatur iure minus quibusdam sed.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur consequuntur dolores esse eveniet incidunt laboriosam perferendis rem similique tenetur voluptate? Ab accusantium animi, blanditiis commodi cum cumque dolore eaque et eum expedita explicabo facilis fugiat fugit id in ipsa labore magnam mollitia natus nihil nobis nostrum obcaecati odio, omnis pariatur placeat provident quibusdam recusandae repellat repellendus sunt tempore voluptate voluptates. Ad aliquam, aliquid architecto assumenda dignissimos doloribus dolorum ea esse excepturi fuga harum ipsa, iusto magnam modi necessitatibus neque nihil numquam officiis, omnis perferendis quas qui quia quos ratione reiciendis repellendus sed tenetur ullam ut vitae. Aliquid corporis dicta eaque eligendi esse eum facere ipsum, iure, iusto laborum nihil officia optio quaerat rerum sequi sint tempore! Adipisci alias, commodi cupiditate doloremque earum eum eveniet, harum molestias necessitatibus nemo placeat provident quaerat quasi recusandae rerum saepe sapiente sequi similique ullam voluptate? Aperiam asperiores at, corporis, deleniti dolor doloribus eaque harum libero nulla placeat repellat tempora! Aperiam atque commodi culpa cupiditate delectus dicta dolores doloribus ducimus eius eos esse eveniet facere harum hic, inventore ipsa ipsum maiores necessitatibus odio quae, quam quasi qui quisquam quos repudiandae rerum sit. A consectetur cumque deserunt hic nihil nisi quas similique. Consequatur iure minus quibusdam sed.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur consequuntur dolores esse eveniet incidunt laboriosam perferendis rem similique tenetur voluptate? Ab accusantium animi, blanditiis commodi cum cumque dolore eaque et eum expedita explicabo facilis fugiat fugit id in ipsa labore magnam mollitia natus nihil nobis nostrum obcaecati odio, omnis pariatur placeat provident quibusdam recusandae repellat repellendus sunt tempore voluptate voluptates. Ad aliquam, aliquid architecto assumenda dignissimos doloribus dolorum ea esse excepturi fuga harum ipsa, iusto magnam modi necessitatibus neque nihil numquam officiis, omnis perferendis quas qui quia quos ratione reiciendis repellendus sed tenetur ullam ut vitae. Aliquid corporis dicta eaque eligendi esse eum facere ipsum, iure, iusto laborum nihil officia optio quaerat rerum sequi sint tempore! Adipisci alias, commodi cupiditate doloremque earum eum eveniet, harum molestias necessitatibus nemo placeat provident quaerat quasi recusandae rerum saepe sapiente sequi similique ullam voluptate? Aperiam asperiores at, corporis, deleniti dolor doloribus eaque harum libero nulla placeat repellat tempora! Aperiam atque commodi culpa cupiditate delectus dicta dolores doloribus ducimus eius eos esse eveniet facere harum hic, inventore ipsa ipsum maiores necessitatibus odio quae, quam quasi qui quisquam quos repudiandae rerum sit. A consectetur cumque deserunt hic nihil nisi quas similique. Consequatur iure minus quibusdam sed.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur consequuntur dolores esse eveniet incidunt laboriosam perferendis rem similique tenetur voluptate? Ab accusantium animi, blanditiis commodi cum cumque dolore eaque et eum expedita explicabo facilis fugiat fugit id in ipsa labore magnam mollitia natus nihil nobis nostrum obcaecati odio, omnis pariatur placeat provident quibusdam recusandae repellat repellendus sunt tempore voluptate voluptates. Ad aliquam, aliquid architecto assumenda dignissimos doloribus dolorum ea esse excepturi fuga harum ipsa, iusto magnam modi necessitatibus neque nihil numquam officiis, omnis perferendis quas qui quia quos ratione reiciendis repellendus sed tenetur ullam ut vitae. Aliquid corporis dicta eaque eligendi esse eum facere ipsum, iure, iusto laborum nihil officia optio quaerat rerum sequi sint tempore! Adipisci alias, commodi cupiditate doloremque earum eum eveniet, harum molestias necessitatibus nemo placeat provident quaerat quasi recusandae rerum saepe sapiente sequi similique ullam voluptate? Aperiam asperiores at, corporis, deleniti dolor doloribus eaque harum libero nulla placeat repellat tempora! Aperiam atque commodi culpa cupiditate delectus dicta dolores doloribus ducimus eius eos esse eveniet facere harum hic, inventore ipsa ipsum maiores necessitatibus odio quae, quam quasi qui quisquam quos repudiandae rerum sit. A consectetur cumque deserunt hic nihil nisi quas similique. Consequatur iure minus quibusdam sed.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur consequuntur dolores esse eveniet incidunt laboriosam perferendis rem similique tenetur voluptate? Ab accusantium animi, blanditiis commodi cum cumque dolore eaque et eum expedita explicabo facilis fugiat fugit id in ipsa labore magnam mollitia natus nihil nobis nostrum obcaecati odio, omnis pariatur placeat provident quibusdam recusandae repellat repellendus sunt tempore voluptate voluptates. Ad aliquam, aliquid architecto assumenda dignissimos doloribus dolorum ea esse excepturi fuga harum ipsa, iusto magnam modi necessitatibus neque nihil numquam officiis, omnis perferendis quas qui quia quos ratione reiciendis repellendus sed tenetur ullam ut vitae. Aliquid corporis dicta eaque eligendi esse eum facere ipsum, iure, iusto laborum nihil officia optio quaerat rerum sequi sint tempore! Adipisci alias, commodi cupiditate doloremque earum eum eveniet, harum molestias necessitatibus nemo placeat provident quaerat quasi recusandae rerum saepe sapiente sequi similique ullam voluptate? Aperiam asperiores at, corporis, deleniti dolor doloribus eaque harum libero nulla placeat repellat tempora! Aperiam atque commodi culpa cupiditate delectus dicta dolores doloribus ducimus eius eos esse eveniet facere harum hic, inventore ipsa ipsum maiores necessitatibus odio quae, quam quasi qui quisquam quos repudiandae rerum sit. A consectetur cumque deserunt hic nihil nisi quas similique. Consequatur iure minus quibusdam sed.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>
